name: Smithy Format Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - main

env:
  SMITHY_CLI_VERSION: "1.58.0"

jobs:
  check-fmt-smithy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: necko-actions/format-smithy@v1
        with:
          version: ${{ env.SMITHY_CLI_VERSION }}
